import type { Animal } from "@/types";

/**
 * DEMO SEED DATA — clearly fictional animals used to demonstrate the
 * platform. Every record carries `demo: true` and the UI labels demo
 * content. Replace via the admin dashboard / Supabase seed in production.
 */
export const DEMO_ANIMALS: Animal[] = [
  {
    id: "d3adbeef-0001-4a01-9c01-000000000001",
    pawsId: "PAWS-KGP-DOG-0012",
    slug: "simba",
    qrToken: "t7kd2mqx",
    name: "Simba",
    species: "dog",
    sex: "male",
    ageLabel: "~3 years",
    color: "Honey tan",
    size: "medium",
    zoneId: "tech-market",
    tagline: "Quiet observer. Professional biscuit negotiator.",
    personality: ["Calm", "Gentle", "Food motivated", "Good with dogs"],
    bio: "Simba spent his first two years keeping a careful distance from people. Volunteers knew him as the tan blur that vanished behind the Technology Market stalls the moment anyone looked his way.\n\nThat changed in April 2026, when he was found with an injured paw and, for the first time, let a volunteer sit beside him. Through three weeks of treatment he learned that hands can be kind. Now he waits near the market every evening — not for food, volunteers insist, but for company. (It is at least partly for food.)\n\nSimba is calm around students, patient with the younger dogs, and has perfected a slow, meaningful stare aimed at anyone holding a biscuit.",
    friendliness: "friendly",
    vaccinated: true,
    sterilized: true,
    healthStatus: "healthy",
    healthNote: "Fully recovered from an April paw injury. Safe & healthy.",
    lastHealthUpdate: "2026-06-28",
    adoption: "available",
    goodWithPeople: true,
    goodWithAnimals: true,
    specialCare: false,
    portrait: {
      from: "#E9C98F",
      to: "#C97F45",
      coat: "#D9A05B",
      coatDark: "#A96F35",
      muzzle: "#F2E3C9",
      ear: "half",
      patch: "left-eye",
      patchColor: "#B37B41",
      tongue: true,
    },
    photos: [
      { id: "sp1", caption: "Evening watch at Technology Market", date: "2026-06-20" },
      { id: "sp2", caption: "First week of paw treatment", date: "2026-04-20" },
      { id: "sp3", caption: "Fully recovered, fully unbothered", date: "2026-05-14" },
    ],
    medicalTimeline: [
      { id: "sm1", date: "2026-03-12", type: "vaccination", title: "Anti-rabies vaccination", note: "Annual booster administered during the spring drive." },
      { id: "sm2", date: "2026-04-18", type: "injury", title: "Minor paw injury reported", note: "Limping reported near Technology Market via a PAWS report." },
      { id: "sm3", date: "2026-04-19", type: "treatment", title: "Treatment started", note: "Wound cleaned and dressed; oral antibiotics for 7 days." },
      { id: "sm4", date: "2026-04-27", type: "recovery", title: "Recovered", note: "Walking normally. Follow-up check clear." },
    ],
    sightings: [
      { id: "ss1", date: "2026-07-08", zoneId: "tech-market", note: "Evening feeding round — ate well, coat looking healthy." },
      { id: "ss2", date: "2026-07-02", zoneId: "nalanda", note: "Spotted trailing the evening feeding cycle rickshaw." },
    ],
    demo: true,
  },
  {
    id: "d3adbeef-0002-4a02-9c02-000000000002",
    pawsId: "PAWS-KGP-DOG-0018",
    slug: "muesli",
    qrToken: "m3sl1vkq",
    name: "Muesli",
    species: "dog",
    sex: "female",
    ageLabel: "~1.5 years",
    color: "Brown & white",
    size: "medium",
    zoneId: "gymkhana",
    tagline: "High energy. Zero understanding of personal space.",
    personality: ["Playful", "Affectionate", "Energetic", "Loves fetch"],
    bio: "Muesli believes every human on campus is her personal friend who simply hasn't been greeted yet. She patrols the Gymkhana grounds at a permanent trot, supervises football practice from the sidelines, and has been formally (affectionately) banned from the badminton court after an incident involving a shuttlecock.\n\nShe was born on campus in early 2025 and hand-raised by a group of hostel volunteers after her mother fell ill. As a result she is deeply people-oriented — which makes her one of our strongest adoption candidates. Muesli needs a family that can match her energy and won't mind a 20-kilogram lap dog.",
    friendliness: "friendly",
    vaccinated: true,
    sterilized: false,
    healthStatus: "healthy",
    healthNote: "Healthy and active. Sterilization scheduled for the August camp.",
    lastHealthUpdate: "2026-07-01",
    adoption: "available",
    goodWithPeople: true,
    goodWithAnimals: true,
    specialCare: false,
    portrait: {
      from: "#E7D6BC",
      to: "#B08968",
      coat: "#A9744C",
      coatDark: "#7C5233",
      muzzle: "#F4EADB",
      ear: "floppy",
      patch: "blaze",
      patchColor: "#F4EADB",
      tongue: true,
    },
    photos: [
      { id: "mp1", caption: "Supervising football practice", date: "2026-06-25" },
      { id: "mp2", caption: "Post-zoomies recovery nap", date: "2026-06-10" },
      { id: "mp3", caption: "With her hostel volunteer crew", date: "2026-05-02" },
    ],
    medicalTimeline: [
      { id: "mm1", date: "2026-02-08", type: "vaccination", title: "Anti-rabies vaccination" },
      { id: "mm2", date: "2026-02-08", type: "deworming", title: "Deworming", note: "Routine quarterly dose." },
      { id: "mm3", date: "2026-06-30", type: "checkup", title: "General health check", note: "Excellent condition. Cleared for sterilization camp." },
    ],
    sightings: [
      { id: "ms1", date: "2026-07-09", zoneId: "gymkhana", note: "Morning feeding — first in line, as always." },
      { id: "ms2", date: "2026-07-05", zoneId: "library", note: "Escorted a group of students to the library steps." },
    ],
    demo: true,
  },
  {
    id: "d3adbeef-0003-4a03-9c03-000000000003",
    pawsId: "PAWS-KGP-DOG-0004",
    slug: "shanti",
    qrToken: "sh4nt1pz",
    name: "Shanti",
    species: "dog",
    sex: "female",
    ageLabel: "~6 years",
    color: "Black",
    size: "medium",
    zoneId: "main-building",
    tagline: "The unofficial dean of the Main Building steps.",
    personality: ["Calm", "Dignified", "Gentle", "Independent"],
    bio: "Shanti has held her post at the Main Building steps longer than most students have held their ID cards. Generations of batches know her; she appears in more convocation photos than some faculty members.\n\nShe is a classic community dog — deeply bonded to her territory and her people, and happiest exactly where she is. PAWS supports her with regular meals, annual vaccination, and now, in her senior years, joint checkups. She is not seeking adoption; the campus is her home. What she asks of you is simple: walk past slowly, and if you have a moment, say good morning.",
    friendliness: "friendly",
    vaccinated: true,
    sterilized: true,
    healthStatus: "monitoring",
    healthNote: "Senior wellness monitoring — mild stiffness in the hind legs, managed with supplements.",
    lastHealthUpdate: "2026-06-15",
    adoption: "not_available",
    goodWithPeople: true,
    goodWithAnimals: true,
    specialCare: true,
    portrait: {
      from: "#C9CBC4",
      to: "#6E7570",
      coat: "#3A3E3B",
      coatDark: "#232724",
      muzzle: "#8E9490",
      ear: "half",
      tongue: false,
    },
    photos: [
      { id: "hp1", caption: "Morning post, Main Building steps", date: "2026-06-12" },
      { id: "hp2", caption: "Convocation day cameo", date: "2025-12-20" },
      { id: "hp3", caption: "Senior wellness checkup", date: "2026-06-15" },
    ],
    medicalTimeline: [
      { id: "hm1", date: "2026-01-20", type: "vaccination", title: "Anti-rabies vaccination" },
      { id: "hm2", date: "2026-06-15", type: "checkup", title: "Senior wellness check", note: "Mild hind-leg stiffness. Joint supplements started; re-check in 3 months." },
    ],
    sightings: [
      { id: "hs1", date: "2026-07-10", zoneId: "main-building", note: "At her post. Accepted two biscuits, declined further conversation." },
    ],
    demo: true,
  },
  {
    id: "d3adbeef-0004-4a04-9c04-000000000004",
    pawsId: "PAWS-KGP-DOG-0021",
    slug: "bunti",
    qrToken: "bnt1w8rd",
    name: "Bunti",
    species: "dog",
    sex: "male",
    ageLabel: "~2 years",
    color: "Brindle",
    size: "medium",
    zoneId: "rk-hall",
    tagline: "Tail first, thinks later.",
    personality: ["Enthusiastic", "Clumsy", "Loyal", "Food motivated"],
    bio: "Bunti greets the world tail-first — the rest of him catches up eventually. He adopted the RK Hall mess as his headquarters and its residents as his staff, a role he takes seriously at exactly two times of day: lunch and dinner.\n\nIn May 2026 volunteers noticed him scratching constantly and losing fur along his back. He was diagnosed with a treatable skin condition and has been on medicated baths since — which he tolerates with the expression of a deeply wronged soul. His coat is growing back well.\n\nBunti would thrive in a foster home while he finishes treatment: somewhere calm, with a soft floor and a predictable food schedule. His gratitude, and a lifetime supply of tail wags, are guaranteed.",
    friendliness: "friendly",
    vaccinated: true,
    sterilized: true,
    healthStatus: "under_treatment",
    healthNote: "Skin condition responding well to medicated baths. Foster home would speed recovery.",
    lastHealthUpdate: "2026-07-06",
    adoption: "foster_needed",
    goodWithPeople: true,
    goodWithAnimals: false,
    specialCare: true,
    portrait: {
      from: "#D8C3A5",
      to: "#8C6A4F",
      coat: "#8A6644",
      coatDark: "#5E432C",
      muzzle: "#E8D9C2",
      ear: "floppy",
      patch: "right-eye",
      patchColor: "#5E432C",
      tongue: true,
    },
    photos: [
      { id: "bp1", caption: "HQ: the RK Hall mess entrance", date: "2026-06-18" },
      { id: "bp2", caption: "Medicated bath day (deeply wronged)", date: "2026-06-29" },
      { id: "bp3", caption: "Coat growing back", date: "2026-07-06" },
    ],
    medicalTimeline: [
      { id: "bm1", date: "2026-01-15", type: "vaccination", title: "Anti-rabies vaccination" },
      { id: "bm2", date: "2026-05-22", type: "injury", title: "Skin condition reported", note: "Hair loss and scratching along the back, reported by RK Hall residents." },
      { id: "bm3", date: "2026-05-24", type: "treatment", title: "Treatment started", note: "Weekly medicated baths and skin supplement." },
      { id: "bm4", date: "2026-07-06", type: "checkup", title: "Progress check", note: "Visible regrowth. Continue baths for 4 more weeks." },
    ],
    sightings: [
      { id: "bs1", date: "2026-07-07", zoneId: "rk-hall", note: "On duty at the mess. Skin visibly better." },
    ],
    demo: true,
  },
  {
    id: "d3adbeef-0005-4a05-9c05-000000000005",
    pawsId: "PAWS-KGP-DOG-0033",
    slug: "laika",
    qrToken: "l4ik9puq",
    name: "Laika",
    species: "dog",
    sex: "female",
    ageLabel: "~4 months",
    color: "Fawn",
    size: "small",
    zoneId: "nalanda",
    tagline: "Small. Loud. Convinced she runs Nalanda.",
    personality: ["Bold", "Curious", "Vocal", "Playful"],
    bio: "Laika is the sole survivor of a litter found behind the Nalanda complex during the March rains. She was two weeks old, soaked, and furious about it — a temperament she has retained.\n\nBottle-fed by volunteers, she has grown into a confident, curious puppy who investigates everything, argues with pigeons, and has never once lost a staring contest. She is at the perfect age to join a family: young enough to adapt instantly, old enough to be past the fragile stage.\n\nHer vaccination course is underway. Whoever adopts Laika is not getting a pet; they are getting a very small manager.",
    friendliness: "friendly",
    vaccinated: true,
    sterilized: false,
    healthStatus: "healthy",
    healthNote: "Thriving. Second vaccination dose completed; final dose due in 3 weeks.",
    lastHealthUpdate: "2026-07-03",
    adoption: "available",
    goodWithPeople: true,
    goodWithAnimals: true,
    specialCare: false,
    portrait: {
      from: "#F2DEB8",
      to: "#D19A5B",
      coat: "#E0B375",
      coatDark: "#B3854A",
      muzzle: "#F7ECD8",
      ear: "pointed",
      tongue: true,
    },
    photos: [
      { id: "lp1", caption: "Week two: small and furious", date: "2026-03-30" },
      { id: "lp2", caption: "First solo meal", date: "2026-05-01" },
      { id: "lp3", caption: "Arguing with pigeons (ongoing)", date: "2026-06-27" },
    ],
    medicalTimeline: [
      { id: "lm1", date: "2026-03-28", type: "treatment", title: "Rescued & stabilised", note: "Found hypothermic after heavy rain; hand-rearing started." },
      { id: "lm2", date: "2026-05-30", type: "vaccination", title: "First vaccination dose" },
      { id: "lm3", date: "2026-07-03", type: "vaccination", title: "Second vaccination dose", note: "Final dose scheduled late July." },
    ],
    sightings: [
      { id: "ls1", date: "2026-07-09", zoneId: "nalanda", note: "Attempted to herd a cycle. Unsuccessful but undeterred." },
    ],
    demo: true,
  },
  {
    id: "d3adbeef-0006-4a06-9c06-000000000006",
    pawsId: "PAWS-KGP-CAT-0007",
    slug: "percy",
    qrToken: "prc7xt2n",
    name: "Percy",
    species: "cat",
    sex: "male",
    ageLabel: "~2 years",
    color: "Grey tabby",
    size: "small",
    zoneId: "library",
    tagline: "Sits on books. Judges silently.",
    personality: ["Calm", "Observant", "Selective", "Lap connoisseur"],
    bio: "Percy operates out of the Central Library, where he has appointed himself Head of Quality Control. His duties include sitting on whichever book you are currently reading, inspecting every bag left unattended, and holding open auditions for The Lap.\n\nHe arrived on campus as a scrawny kitten in 2024 and worked his way up through sheer composure. He is vaccinated, sterilized, and in excellent health — and unlike most library regulars, he is available for adoption. Percy would suit a quiet home with a reading habit and at least one high shelf.",
    friendliness: "selective",
    vaccinated: true,
    sterilized: true,
    healthStatus: "healthy",
    healthNote: "Excellent condition. Annual checkup complete.",
    lastHealthUpdate: "2026-06-05",
    adoption: "available",
    goodWithPeople: true,
    goodWithAnimals: false,
    specialCare: false,
    portrait: {
      from: "#D5D9D2",
      to: "#7E8C86",
      coat: "#98A29A",
      coatDark: "#5F6A63",
      muzzle: "#E6EAE3",
      ear: "pointed",
      patch: "blaze",
      patchColor: "#E6EAE3",
      tongue: false,
    },
    photos: [
      { id: "pp1", caption: "Quality control, reading room", date: "2026-06-20" },
      { id: "pp2", caption: "The shelf of judgement", date: "2026-05-11" },
      { id: "pp3", caption: "Lap audition in progress", date: "2026-04-02" },
    ],
    medicalTimeline: [
      { id: "pm1", date: "2026-01-11", type: "vaccination", title: "Annual vaccination" },
      { id: "pm2", date: "2025-08-19", type: "sterilization", title: "Sterilized", note: "Routine recovery, back on duty in 48 hours." },
      { id: "pm3", date: "2026-06-05", type: "checkup", title: "Annual health check", note: "Excellent condition." },
    ],
    sightings: [
      { id: "ps1", date: "2026-07-08", zoneId: "library", note: "Occupied the new-arrivals shelf for most of the afternoon." },
    ],
    demo: true,
  },
  {
    id: "d3adbeef-0007-4a07-9c07-000000000007",
    pawsId: "PAWS-KGP-CAT-0011",
    slug: "mishti",
    qrToken: "msht5ye3",
    name: "Mishti",
    species: "cat",
    sex: "female",
    ageLabel: "~1 year",
    color: "Calico",
    size: "small",
    zoneId: "vs-hall",
    tagline: "Softest meow on campus. Uses it responsibly.",
    personality: ["Sweet", "Shy at first", "Gentle", "Curious"],
    bio: "Mishti announced herself to VS Hall with a meow so quiet that three students initially thought they were imagining it. She wasn't imaginary — just small, hungry, and nursing a badly infected eye.\n\nTwo months of patient treatment later, both eyes are bright and the meow remains at library volume. She has become the hall's gentle background presence: appearing at study tables during exam week, accepting chin scratches as payment.\n\nMishti is recovering well but would heal fastest in a foster home. She is quiet, clean, and asks very little of the world — which is exactly why she deserves a lot.",
    friendliness: "shy",
    vaccinated: true,
    sterilized: false,
    healthStatus: "recovering",
    healthNote: "Eye infection fully treated; final follow-up due mid-July. Foster home preferred during recovery.",
    lastHealthUpdate: "2026-07-02",
    adoption: "foster_needed",
    goodWithPeople: true,
    goodWithAnimals: true,
    specialCare: true,
    portrait: {
      from: "#F0DCC8",
      to: "#C48A5A",
      coat: "#E3C49B",
      coatDark: "#9A6B3F",
      muzzle: "#F8EEDF",
      ear: "pointed",
      patch: "right-eye",
      patchColor: "#9A6B3F",
      tongue: false,
    },
    photos: [
      { id: "mip1", caption: "Exam-week study companion", date: "2026-04-28" },
      { id: "mip2", caption: "Both eyes open — recovery photo", date: "2026-06-25" },
      { id: "mip3", caption: "Chin scratch payment accepted", date: "2026-07-01" },
    ],
    medicalTimeline: [
      { id: "mim1", date: "2026-05-02", type: "injury", title: "Eye infection reported", note: "Severe infection, left eye. Reported by VS Hall residents." },
      { id: "mim2", date: "2026-05-03", type: "treatment", title: "Treatment started", note: "Antibiotic drops and supportive care." },
      { id: "mim3", date: "2026-06-25", type: "recovery", title: "Infection cleared", note: "Both eyes healthy. Final follow-up mid-July." },
      { id: "mim4", date: "2026-06-25", type: "vaccination", title: "Vaccination", note: "Administered after recovery." },
    ],
    sightings: [
      { id: "mis1", date: "2026-07-06", zoneId: "vs-hall", note: "Evening feeding — confident, eyes clear." },
    ],
    demo: true,
  },
  {
    id: "d3adbeef-0008-4a08-9c08-000000000008",
    pawsId: "PAWS-KGP-DOG-0027",
    slug: "rocket",
    qrToken: "rkt8vz4a",
    name: "Rocket",
    species: "dog",
    sex: "male",
    ageLabel: "~2 years",
    color: "White & tan",
    size: "medium",
    zoneId: "main-gate",
    tagline: "Fast. Cautious. Faster when cautious.",
    personality: ["Alert", "Cautious", "Independent", "Smart"],
    bio: "Rocket earned his name the day a volunteer tried to photograph him and captured, in four consecutive frames, an empty road. He is the Main Gate area's early-warning system — nothing enters campus without his knowledge, and nothing gets within ten metres of him without his consent.\n\nHe is a healthy, self-sufficient community dog who accepts food on his own terms and vaccination only under expert-level negotiation. PAWS monitors him from a respectful distance, which he appreciates. Rocket is not seeking a family; he has a job.",
    friendliness: "cautious",
    vaccinated: true,
    sterilized: false,
    healthStatus: "healthy",
    healthNote: "Healthy. Sterilization planned once trust-building allows safe handling.",
    lastHealthUpdate: "2026-06-10",
    adoption: "not_available",
    goodWithPeople: false,
    goodWithAnimals: true,
    specialCare: false,
    portrait: {
      from: "#EDE4D3",
      to: "#B59B77",
      coat: "#E8DCC6",
      coatDark: "#B08D5F",
      muzzle: "#F8F2E6",
      ear: "pointed",
      patch: "left-eye",
      patchColor: "#C9A063",
      tongue: false,
    },
    photos: [
      { id: "rp1", caption: "Rare stationary sighting", date: "2026-05-15" },
      { id: "rp2", caption: "On duty, Main Gate", date: "2026-06-08" },
    ],
    medicalTimeline: [
      { id: "rm1", date: "2026-02-26", type: "vaccination", title: "Anti-rabies vaccination", note: "Administered during the gate-area drive. Negotiations were extensive." },
      { id: "rm2", date: "2026-06-10", type: "checkup", title: "Visual health assessment", note: "Assessed from distance — excellent condition." },
    ],
    sightings: [
      { id: "rs1", date: "2026-07-10", zoneId: "main-gate", note: "Patrolling. Acknowledged volunteers with one (1) tail wag." },
    ],
    demo: true,
  },
];

export function getDemoAnimal(slug: string) {
  return DEMO_ANIMALS.find((a) => a.slug === slug);
}

export function getDemoAnimalByToken(token: string) {
  return DEMO_ANIMALS.find((a) => a.qrToken === token);
}
