import type { Animal } from "@/types";

/**
 * DEMO SEED DATA — clearly fictional animals used to demonstrate the
 * platform. Every record carries `demo: true` and the UI labels demo
 * content. Replace via the admin dashboard / Supabase seed in production.
 */
export const DEMO_ANIMALS: Animal[] = [
  {
    id: "d3adbeef-0001-4a01-9c01-000000000001",
    pawsId: "PAWS-KGP-DOG-0012",
    slug: "simba",
    qrToken: "t7kd2mqx",
    name: "Simba",
    species: "dog",
    sex: "male",
    ageLabel: "~3 years",
    color: "Honey tan",
    size: "medium",
    zoneId: "tech-market",
    tagline: "Quiet observer. Professional biscuit negotiator.",
    personality: ["Calm", "Gentle", "Food motivated", "Good with dogs"],
    bio: "Simba spent his first two years keeping a careful distance from people. Volunteers knew him as the tan blur that vanished behind the Technology Market stalls the moment anyone looked his way.\n\nThat changed in April 2026, when he was found with an injured paw and, for the first time, let a volunteer sit beside him. Through three weeks of treatment he learned that hands can be kind. Now he waits near the market every evening — not for food, volunteers insist, but for company. (It is at least partly for food.)\n\nSimba is calm around students, patient with the younger dogs, and has perfected a slow, meaningful stare aimed at anyone holding a biscuit.",
    friendliness: "friendly",
    vaccinated: true,
    sterilized: true,
    healthStatus: "healthy",
    healthNote: "Fully recovered from an April paw injury. Safe & healthy.",
    lastHealthUpdate: "2026-06-28",
    adoption: "available",
    goodWithPeople: true,
    goodWithAnimals: true,
    specialCare: false,
    portrait: {
      from: "#E9C98F",
      to: "#C97F45",
      coat: "#D9A05B",
      coatDark: "#A96F35",
      muzzle: "#F2E3C9",
      ear: "half",
      patch: "left-eye",
      patchColor: "#B37B41",
      tongue: true,
    },
    photos: [
      { id: "sp1", url: "/images/adopt/simba.jpg", caption: "Evening watch at Technology Market", date: "2026-06-20" },
      { id: "sp2", caption: "First week of paw treatment", date: "2026-04-20" },
      { id: "sp3", caption: "Fully recovered, fully unbothered", date: "2026-05-14" },
    ],
    medicalTimeline: [
      { id: "sm1", date: "2026-03-12", type: "vaccination", title: "Anti-rabies vaccination", note: "Annual booster administered during the spring drive." },
      { id: "sm2", date: "2026-04-18", type: "injury", title: "Minor paw injury reported", note: "Limping reported near Technology Market via a PAWS report." },
      { id: "sm3", date: "2026-04-19", type: "treatment", title: "Treatment started", note: "Wound cleaned and dressed; oral antibiotics for 7 days." },
      { id: "sm4", date: "2026-04-27", type: "recovery", title: "Recovered", note: "Walking normally. Follow-up check clear." },
    ],
    sightings: [
      { id: "ss1", date: "2026-07-08", zoneId: "tech-market", note: "Evening feeding round — ate well, coat looking healthy." },
      { id: "ss2", date: "2026-07-02", zoneId: "nalanda", note: "Spotted trailing the evening feeding cycle rickshaw." },
    ],
    demo: true,
  },
  {
    id: "d3adbeef-0003-4a03-9c03-000000000003",
    pawsId: "PAWS-KGP-DOG-0004",
    slug: "shanti",
    qrToken: "sh4nt1pz",
    name: "Shanti",
    species: "dog",
    sex: "female",
    ageLabel: "~6 years",
    color: "Black",
    size: "medium",
    zoneId: "main-building",
    tagline: "The unofficial dean of the Main Building steps.",
    personality: ["Calm", "Dignified", "Gentle", "Independent"],
    bio: "Shanti has held her post at the Main Building steps longer than most students have held their ID cards. Generations of batches know her; she appears in more convocation photos than some faculty members.\n\nShe is a classic community dog — deeply bonded to her territory and her people, and happiest exactly where she is. PAWS supports her with regular meals, annual vaccination, and now, in her senior years, joint checkups. She is not seeking adoption; the campus is her home. What she asks of you is simple: walk past slowly, and if you have a moment, say good morning.",
    friendliness: "friendly",
    vaccinated: true,
    sterilized: true,
    healthStatus: "monitoring",
    healthNote: "Senior wellness monitoring — mild stiffness in the hind legs, managed with supplements.",
    lastHealthUpdate: "2026-06-15",
    adoption: "not_available",
    goodWithPeople: true,
    goodWithAnimals: true,
    specialCare: true,
    portrait: {
      from: "#C9CBC4",
      to: "#6E7570",
      coat: "#3A3E3B",
      coatDark: "#232724",
      muzzle: "#8E9490",
      ear: "half",
      tongue: false,
    },
    photos: [
      { id: "hp1", url: "/images/adopt/shanti.jpg", caption: "Morning post, Main Building steps", date: "2026-06-12" },
      { id: "hp2", caption: "Convocation day cameo", date: "2025-12-20" },
      { id: "hp3", caption: "Senior wellness checkup", date: "2026-06-15" },
    ],
    medicalTimeline: [
      { id: "hm1", date: "2026-01-20", type: "vaccination", title: "Anti-rabies vaccination" },
      { id: "hm2", date: "2026-06-15", type: "checkup", title: "Senior wellness check", note: "Mild hind-leg stiffness. Joint supplements started; re-check in 3 months." },
    ],
    sightings: [
      { id: "hs1", date: "2026-07-10", zoneId: "main-building", note: "At her post. Accepted two biscuits, declined further conversation." },
    ],
    demo: true,
  },
  {
    id: "d3adbeef-0005-4a05-9c05-000000000005",
    pawsId: "PAWS-KGP-DOG-0033",
    slug: "laika",
    qrToken: "l4ik9puq",
    name: "Laika",
    species: "dog",
    sex: "female",
    ageLabel: "~4 months",
    color: "Fawn",
    size: "small",
    zoneId: "nalanda",
    tagline: "Small. Loud. Convinced she runs Nalanda.",
    personality: ["Bold", "Curious", "Vocal", "Playful"],
    bio: "Laika is the sole survivor of a litter found behind the Nalanda complex during the March rains. She was two weeks old, soaked, and furious about it — a temperament she has retained.\n\nBottle-fed by volunteers, she has grown into a confident, curious puppy who investigates everything, argues with pigeons, and has never once lost a staring contest. She is at the perfect age to join a family: young enough to adapt instantly, old enough to be past the fragile stage.\n\nHer vaccination course is underway. Whoever adopts Laika is not getting a pet; they are getting a very small manager.",
    friendliness: "friendly",
    vaccinated: true,
    sterilized: false,
    healthStatus: "healthy",
    healthNote: "Thriving. Second vaccination dose completed; final dose due in 3 weeks.",
    lastHealthUpdate: "2026-07-03",
    adoption: "available",
    goodWithPeople: true,
    goodWithAnimals: true,
    specialCare: false,
    portrait: {
      from: "#F2DEB8",
      to: "#D19A5B",
      coat: "#E0B375",
      coatDark: "#B3854A",
      muzzle: "#F7ECD8",
      ear: "pointed",
      tongue: true,
    },
    photos: [
      { id: "lp1", url: "/images/adopt/laika.jpg", caption: "Week two: small and furious", date: "2026-03-30" },
      { id: "lp2", caption: "First solo meal", date: "2026-05-01" },
      { id: "lp3", caption: "Arguing with pigeons (ongoing)", date: "2026-06-27" },
    ],
    medicalTimeline: [
      { id: "lm1", date: "2026-03-28", type: "treatment", title: "Rescued & stabilised", note: "Found hypothermic after heavy rain; hand-rearing started." },
      { id: "lm2", date: "2026-05-30", type: "vaccination", title: "First vaccination dose" },
      { id: "lm3", date: "2026-07-03", type: "vaccination", title: "Second vaccination dose", note: "Final dose scheduled late July." },
    ],
    sightings: [
      { id: "ls1", date: "2026-07-09", zoneId: "nalanda", note: "Attempted to herd a cycle. Unsuccessful but undeterred." },
    ],
    demo: true,
  },
  {
    id: "d3adbeef-0008-4a08-9c08-000000000008",
    pawsId: "PAWS-KGP-DOG-0027",
    slug: "rocket",
    qrToken: "rkt8vz4a",
    name: "Rocket",
    species: "dog",
    sex: "male",
    ageLabel: "~2 years",
    color: "White & tan",
    size: "medium",
    zoneId: "main-gate",
    tagline: "Fast. Cautious. Faster when cautious.",
    personality: ["Alert", "Cautious", "Independent", "Smart"],
    bio: "Rocket earned his name the day a volunteer tried to photograph him and captured, in four consecutive frames, an empty road. He is the Main Gate area's early-warning system — nothing enters campus without his knowledge, and nothing gets within ten metres of him without his consent.\n\nHe is a healthy, self-sufficient community dog who accepts food on his own terms and vaccination only under expert-level negotiation. PAWS monitors him from a respectful distance, which he appreciates. Rocket is not seeking a family; he has a job.",
    friendliness: "cautious",
    vaccinated: true,
    sterilized: false,
    healthStatus: "healthy",
    healthNote: "Healthy. Sterilization planned once trust-building allows safe handling.",
    lastHealthUpdate: "2026-06-10",
    adoption: "not_available",
    goodWithPeople: false,
    goodWithAnimals: true,
    specialCare: false,
    portrait: {
      from: "#EDE4D3",
      to: "#B59B77",
      coat: "#E8DCC6",
      coatDark: "#B08D5F",
      muzzle: "#F8F2E6",
      ear: "pointed",
      patch: "left-eye",
      patchColor: "#C9A063",
      tongue: false,
    },
    photos: [
      { id: "rp1", url: "/images/adopt/rocket.jpg", caption: "Rare stationary sighting", date: "2026-05-15" },
      { id: "rp2", caption: "On duty, Main Gate", date: "2026-06-08" },
    ],
    medicalTimeline: [
      { id: "rm1", date: "2026-02-26", type: "vaccination", title: "Anti-rabies vaccination", note: "Administered during the gate-area drive. Negotiations were extensive." },
      { id: "rm2", date: "2026-06-10", type: "checkup", title: "Visual health assessment", note: "Assessed from distance — excellent condition." },
    ],
    sightings: [
      { id: "rs1", date: "2026-07-10", zoneId: "main-gate", note: "Patrolling. Acknowledged volunteers with one (1) tail wag." },
    ],
    demo: true,
  },
];

export function getDemoAnimal(slug: string) {
  return DEMO_ANIMALS.find((a) => a.slug === slug);
}

export function getDemoAnimalByToken(token: string) {
  return DEMO_ANIMALS.find((a) => a.qrToken === token);
}
